/* GL/GLX stub library for cross-compilation - 967 functions */

void glAccum() { }
void glActiveTexture() { }
void glActiveTextureARB() { }
void glAlphaFragmentOp1ATI() { }
void glAlphaFragmentOp2ATI() { }
void glAlphaFragmentOp3ATI() { }
void glAlphaFunc() { }
unsigned char glAreTexturesResident() { return 0; }
unsigned char glAreTexturesResidentEXT() { return 0; }
void glArrayElement() { }
void glArrayElementEXT() { }
void glArrayObjectATI() { }
void glAsyncMarkerSGIX() { }
void glBegin() { }
void glBeginFragmentShaderATI() { }
void glBeginOcclusionQueryNV() { }
void glBeginVertexShaderEXT() { }
void glBindFragmentShaderATI() { }
unsigned int glBindLightParameterEXT() { return 0; }
unsigned int glBindMaterialParameterEXT() { return 0; }
unsigned int glBindParameterEXT() { return 0; }
void glBindProgramARB() { }
unsigned int glBindTexGenParameterEXT() { return 0; }
void glBindTexture() { }
void glBindTextureEXT() { }
unsigned int glBindTextureUnitParameterEXT() { return 0; }
void glBindVertexShaderEXT() { }
void glBitmap() { }
void glBlendColor() { }
void glBlendColorEXT() { }
void glBlendEquation() { }
void glBlendEquationEXT() { }
void glBlendFunc() { }
void glBlendFuncSeparate() { }
void glBlendFuncSeparateEXT() { }
void glCallList() { }
void glCallLists() { }
void glClear() { }
void glClearAccum() { }
void glClearColor() { }
void glClearDepth() { }
void glClearIndex() { }
void glClearStencil() { }
void glClientActiveTexture() { }
void glClientActiveTextureARB() { }
void glClientActiveVertexStreamATI() { }
void glClipPlane() { }
void glColor3b() { }
void glColor3bv() { }
void glColor3d() { }
void glColor3dv() { }
void glColor3f() { }
void glColor3fv() { }
void glColor3i() { }
void glColor3iv() { }
void glColor3s() { }
void glColor3sv() { }
void glColor3ub() { }
void glColor3ubv() { }
void glColor3ui() { }
void glColor3uiv() { }
void glColor3us() { }
void glColor3usv() { }
void glColor4b() { }
void glColor4bv() { }
void glColor4d() { }
void glColor4dv() { }
void glColor4f() { }
void glColor4fv() { }
void glColor4i() { }
void glColor4iv() { }
void glColor4s() { }
void glColor4sv() { }
void glColor4ub() { }
void glColor4ubv() { }
void glColor4ui() { }
void glColor4uiv() { }
void glColor4us() { }
void glColor4usv() { }
void glColorFragmentOp1ATI() { }
void glColorFragmentOp2ATI() { }
void glColorFragmentOp3ATI() { }
void glColorMask() { }
void glColorMaterial() { }
void glColorPointer() { }
void glColorPointerEXT() { }
void glColorSubTable() { }
void glColorTable() { }
void glColorTableParameterfv() { }
void glColorTableParameterfvSGI() { }
void glColorTableParameteriv() { }
void glColorTableParameterivSGI() { }
void glColorTableSGI() { }
void glCompressedTexImage1D() { }
void glCompressedTexImage1DARB() { }
void glCompressedTexImage2D() { }
void glCompressedTexImage2DARB() { }
void glCompressedTexImage3D() { }
void glCompressedTexImage3DARB() { }
void glCompressedTexSubImage1D() { }
void glCompressedTexSubImage1DARB() { }
void glCompressedTexSubImage2D() { }
void glCompressedTexSubImage2DARB() { }
void glCompressedTexSubImage3D() { }
void glCompressedTexSubImage3DARB() { }
void glConvolutionFilter1D() { }
void glConvolutionFilter1DEXT() { }
void glConvolutionFilter2D() { }
void glConvolutionFilter2DEXT() { }
void glConvolutionParameterf() { }
void glConvolutionParameterfEXT() { }
void glConvolutionParameterfv() { }
void glConvolutionParameterfvEXT() { }
void glConvolutionParameteri() { }
void glConvolutionParameteriEXT() { }
void glConvolutionParameteriv() { }
void glConvolutionParameterivEXT() { }
void glCopyColorSubTable() { }
void glCopyColorTable() { }
void glCopyColorTableSGI() { }
void glCopyConvolutionFilter1D() { }
void glCopyConvolutionFilter1DEXT() { }
void glCopyConvolutionFilter2D() { }
void glCopyConvolutionFilter2DEXT() { }
void glCopyPixels() { }
void glCopyTexImage1D() { }
void glCopyTexImage1DEXT() { }
void glCopyTexImage2D() { }
void glCopyTexImage2DEXT() { }
void glCopyTexSubImage1D() { }
void glCopyTexSubImage1DEXT() { }
void glCopyTexSubImage2D() { }
void glCopyTexSubImage2DEXT() { }
void glCopyTexSubImage3D() { }
void glCopyTexSubImage3DEXT() { }
void glCullFace() { }
void glDeformSGIX() { }
void glDeformationMap3dSGIX() { }
void glDeformationMap3fSGIX() { }
void glDeleteAsyncMarkersSGIX() { }
void glDeleteFragmentShaderATI() { }
void glDeleteLists() { }
void glDeleteObjectBufferATI() { }
void glDeleteOcclusionQueriesNV() { }
void glDeleteProgramsARB() { }
void glDeleteTextures() { }
void glDeleteTexturesEXT() { }
void glDeleteVertexShaderEXT() { }
void glDepthFunc() { }
void glDepthMask() { }
void glDepthRange() { }
void glDetailTexFuncSGIS() { }
void glDisable() { }
void glDisableClientState() { }
void glDisableVariantClientStateEXT() { }
void glDisableVertexAttribArrayARB() { }
void glDrawArrays() { }
void glDrawArraysEXT() { }
void glDrawBuffer() { }
void glDrawBuffersATI() { }
void glDrawElementArrayATI() { }
void glDrawElements() { }
void glDrawPixels() { }
void glDrawRangeElementArrayATI() { }
void glDrawRangeElements() { }
void glEdgeFlag() { }
void glEdgeFlagPointer() { }
void glEdgeFlagPointerEXT() { }
void glEdgeFlagv() { }
void glElementPointerATI() { }
void glEnable() { }
void glEnableClientState() { }
void glEnableVariantClientStateEXT() { }
void glEnableVertexAttribArrayARB() { }
void glEnd() { }
void glEndFragmentShaderATI() { }
void glEndList() { }
void glEndOcclusionQueryNV() { }
void glEndVertexShaderEXT() { }
void glEvalCoord1d() { }
void glEvalCoord1dv() { }
void glEvalCoord1f() { }
void glEvalCoord1fv() { }
void glEvalCoord2d() { }
void glEvalCoord2dv() { }
void glEvalCoord2f() { }
void glEvalCoord2fv() { }
void glEvalMesh1() { }
void glEvalMesh2() { }
void glEvalPoint1() { }
void glEvalPoint2() { }
void glExtractComponentEXT() { }
void glFeedbackBuffer() { }
void glFinish() { }
unsigned int glFinishAsyncSGIX() { return 0; }
void glFlush() { }
void glFlushRasterSGIX() { }
void glFogCoordPointer() { }
void glFogCoordPointerEXT() { }
void glFogCoordd() { }
void glFogCoorddEXT() { }
void glFogCoorddv() { }
void glFogCoorddvEXT() { }
void glFogCoordf() { }
void glFogCoordfEXT() { }
void glFogCoordfv() { }
void glFogCoordfvEXT() { }
void glFogFuncSGIS() { }
void glFogf() { }
void glFogfv() { }
void glFogi() { }
void glFogiv() { }
void glFragmentColorMaterialSGIX() { }
void glFragmentLightModelfSGIX() { }
void glFragmentLightModelfvSGIX() { }
void glFragmentLightModeliSGIX() { }
void glFragmentLightModelivSGIX() { }
void glFragmentLightfSGIX() { }
void glFragmentLightfvSGIX() { }
void glFragmentLightiSGIX() { }
void glFragmentLightivSGIX() { }
void glFragmentMaterialfSGIX() { }
void glFragmentMaterialfvSGIX() { }
void glFragmentMaterialiSGIX() { }
void glFragmentMaterialivSGIX() { }
void glFrameZoomSGIX() { }
void glFrontFace() { }
void glFrustum() { }
unsigned int glGenAsyncMarkersSGIX() { return 0; }
unsigned int glGenFragmentShadersATI() { return 0; }
unsigned int glGenLists() { return 0; }
void glGenOcclusionQueriesNV() { }
void glGenProgramsARB() { }
unsigned int glGenSymbolsEXT() { return 0; }
void glGenTextures() { }
void glGenTexturesEXT() { }
unsigned int glGenVertexShadersEXT() { return 0; }
void glGetArrayObjectfvATI() { }
void glGetArrayObjectivATI() { }
void glGetBooleanv() { }
void glGetClipPlane() { }
void glGetColorTable() { }
void glGetColorTableParameterfv() { }
void glGetColorTableParameterfvSGI() { }
void glGetColorTableParameteriv() { }
void glGetColorTableParameterivSGI() { }
void glGetColorTableSGI() { }
void glGetCompressedTexImage() { }
void glGetCompressedTexImageARB() { }
void glGetConvolutionFilter() { }
void glGetConvolutionFilterEXT() { }
void glGetConvolutionParameterfv() { }
void glGetConvolutionParameterfvEXT() { }
void glGetConvolutionParameteriv() { }
void glGetConvolutionParameterivEXT() { }
void glGetDetailTexFuncSGIS() { }
void glGetDoublev() { }
unsigned int glGetError() { return 0; }
void glGetFloatv() { }
void glGetFogFuncSGIS() { }
void glGetFragmentLightfvSGIX() { }
void glGetFragmentLightivSGIX() { }
void glGetFragmentMaterialfvSGIX() { }
void glGetFragmentMaterialivSGIX() { }
void glGetHistogram() { }
void glGetHistogramEXT() { }
void glGetHistogramParameterfv() { }
void glGetHistogramParameterfvEXT() { }
void glGetHistogramParameteriv() { }
void glGetHistogramParameterivEXT() { }
unsigned int glGetInstrumentsSGIX() { return 0; }
void glGetIntegerv() { }
void glGetInvariantBooleanvEXT() { }
void glGetInvariantFloatvEXT() { }
void glGetInvariantIntegervEXT() { }
void glGetLightfv() { }
void glGetLightiv() { }
void glGetListParameterfvSGIX() { }
void glGetListParameterivSGIX() { }
void glGetLocalConstantBooleanvEXT() { }
void glGetLocalConstantFloatvEXT() { }
void glGetLocalConstantIntegervEXT() { }
void glGetMapdv() { }
void glGetMapfv() { }
void glGetMapiv() { }
void glGetMaterialfv() { }
void glGetMaterialiv() { }
void glGetMinmax() { }
void glGetMinmaxEXT() { }
void glGetMinmaxParameterfv() { }
void glGetMinmaxParameterfvEXT() { }
void glGetMinmaxParameteriv() { }
void glGetMinmaxParameterivEXT() { }
void glGetObjectBufferfvATI() { }
void glGetObjectBufferivATI() { }
void glGetOcclusionQueryivNV() { }
void glGetOcclusionQueryuivNV() { }
void glGetPixelMapfv() { }
void glGetPixelMapuiv() { }
void glGetPixelMapusv() { }
void glGetPixelTexGenParameterfvSGIS() { }
void glGetPixelTexGenParameterivSGIS() { }
void glGetPointerv() { }
void glGetPointervEXT() { }
void glGetPolygonStipple() { }
void glGetProgramEnvParameterdvARB() { }
void glGetProgramEnvParameterfvARB() { }
void glGetProgramLocalParameterdvARB() { }
void glGetProgramLocalParameterfvARB() { }
void glGetProgramStringARB() { }
void glGetProgramivARB() { }
void glGetSeparableFilter() { }
void glGetSeparableFilterEXT() { }
void glGetSharpenTexFuncSGIS() { }
void* glGetString() { return 0; }
void glGetTexBumpParameterfvATI() { }
void glGetTexBumpParameterivATI() { }
void glGetTexEnvfv() { }
void glGetTexEnviv() { }
void glGetTexFilterFuncSGIS() { }
void glGetTexGendv() { }
void glGetTexGenfv() { }
void glGetTexGeniv() { }
void glGetTexImage() { }
void glGetTexLevelParameterfv() { }
void glGetTexLevelParameteriv() { }
void glGetTexParameterfv() { }
void glGetTexParameteriv() { }
void glGetVariantArrayObjectfvATI() { }
void glGetVariantArrayObjectivATI() { }
void glGetVariantBooleanvEXT() { }
void glGetVariantFloatvEXT() { }
void glGetVariantIntegervEXT() { }
void glGetVariantPointervEXT() { }
void glGetVertexAttribArrayObjectfvATI() { }
void glGetVertexAttribArrayObjectivATI() { }
void glGetVertexAttribPointervARB() { }
void glGetVertexAttribdvARB() { }
void glGetVertexAttribfvARB() { }
void glGetVertexAttribivARB() { }
void glHint() { }
void glHistogram() { }
void glHistogramEXT() { }
void glIndexMask() { }
void glIndexPointer() { }
void glIndexPointerEXT() { }
void glIndexd() { }
void glIndexdv() { }
void glIndexf() { }
void glIndexfv() { }
void glIndexi() { }
void glIndexiv() { }
void glIndexs() { }
void glIndexsv() { }
void glIndexub() { }
void glIndexubv() { }
void glInitNames() { }
void glInsertComponentEXT() { }
void glInstrumentsBufferSGIX() { }
void glInterleavedArrays() { }
unsigned char glIsAsyncMarkerSGIX() { return 0; }
unsigned char glIsEnabled() { return 0; }
unsigned char glIsList() { return 0; }
unsigned char glIsObjectBufferATI() { return 0; }
unsigned char glIsOcclusionQueryNV() { return 0; }
unsigned char glIsProgramARB() { return 0; }
unsigned char glIsTexture() { return 0; }
unsigned char glIsTextureEXT() { return 0; }
unsigned char glIsVariantEnabledEXT() { return 0; }
void glLightEnviSGIX() { }
void glLightModelf() { }
void glLightModelfv() { }
void glLightModeli() { }
void glLightModeliv() { }
void glLightf() { }
void glLightfv() { }
void glLighti() { }
void glLightiv() { }
void glLineStipple() { }
void glLineWidth() { }
void glListBase() { }
void glListParameterfSGIX() { }
void glListParameterfvSGIX() { }
void glListParameteriSGIX() { }
void glListParameterivSGIX() { }
void glLoadIdentity() { }
void glLoadIdentityDeformationMapSGIX() { }
void glLoadMatrixd() { }
void glLoadMatrixf() { }
void glLoadName() { }
void glLoadTransposeMatrixd() { }
void glLoadTransposeMatrixdARB() { }
void glLoadTransposeMatrixf() { }
void glLoadTransposeMatrixfARB() { }
void glLockArraysEXT() { }
void glLogicOp() { }
void glMap1d() { }
void glMap1f() { }
void glMap2d() { }
void glMap2f() { }
void glMapGrid1d() { }
void glMapGrid1f() { }
void glMapGrid2d() { }
void glMapGrid2f() { }
void* glMapObjectBufferATI() { return 0; }
void glMaterialf() { }
void glMaterialfv() { }
void glMateriali() { }
void glMaterialiv() { }
void glMatrixMode() { }
void glMinmax() { }
void glMinmaxEXT() { }
void glMultMatrixd() { }
void glMultMatrixf() { }
void glMultTransposeMatrixd() { }
void glMultTransposeMatrixdARB() { }
void glMultTransposeMatrixf() { }
void glMultTransposeMatrixfARB() { }
void glMultiDrawArrays() { }
void glMultiDrawArraysEXT() { }
void glMultiDrawElements() { }
void glMultiDrawElementsEXT() { }
void glMultiTexCoord1d() { }
void glMultiTexCoord1dARB() { }
void glMultiTexCoord1dv() { }
void glMultiTexCoord1dvARB() { }
void glMultiTexCoord1f() { }
void glMultiTexCoord1fARB() { }
void glMultiTexCoord1fv() { }
void glMultiTexCoord1fvARB() { }
void glMultiTexCoord1i() { }
void glMultiTexCoord1iARB() { }
void glMultiTexCoord1iv() { }
void glMultiTexCoord1ivARB() { }
void glMultiTexCoord1s() { }
void glMultiTexCoord1sARB() { }
void glMultiTexCoord1sv() { }
void glMultiTexCoord1svARB() { }
void glMultiTexCoord2d() { }
void glMultiTexCoord2dARB() { }
void glMultiTexCoord2dv() { }
void glMultiTexCoord2dvARB() { }
void glMultiTexCoord2f() { }
void glMultiTexCoord2fARB() { }
void glMultiTexCoord2fv() { }
void glMultiTexCoord2fvARB() { }
void glMultiTexCoord2i() { }
void glMultiTexCoord2iARB() { }
void glMultiTexCoord2iv() { }
void glMultiTexCoord2ivARB() { }
void glMultiTexCoord2s() { }
void glMultiTexCoord2sARB() { }
void glMultiTexCoord2sv() { }
void glMultiTexCoord2svARB() { }
void glMultiTexCoord3d() { }
void glMultiTexCoord3dARB() { }
void glMultiTexCoord3dv() { }
void glMultiTexCoord3dvARB() { }
void glMultiTexCoord3f() { }
void glMultiTexCoord3fARB() { }
void glMultiTexCoord3fv() { }
void glMultiTexCoord3fvARB() { }
void glMultiTexCoord3i() { }
void glMultiTexCoord3iARB() { }
void glMultiTexCoord3iv() { }
void glMultiTexCoord3ivARB() { }
void glMultiTexCoord3s() { }
void glMultiTexCoord3sARB() { }
void glMultiTexCoord3sv() { }
void glMultiTexCoord3svARB() { }
void glMultiTexCoord4d() { }
void glMultiTexCoord4dARB() { }
void glMultiTexCoord4dv() { }
void glMultiTexCoord4dvARB() { }
void glMultiTexCoord4f() { }
void glMultiTexCoord4fARB() { }
void glMultiTexCoord4fv() { }
void glMultiTexCoord4fvARB() { }
void glMultiTexCoord4i() { }
void glMultiTexCoord4iARB() { }
void glMultiTexCoord4iv() { }
void glMultiTexCoord4ivARB() { }
void glMultiTexCoord4s() { }
void glMultiTexCoord4sARB() { }
void glMultiTexCoord4sv() { }
void glMultiTexCoord4svARB() { }
void glNewList() { }
unsigned int glNewObjectBufferATI() { return 0; }
void glNormal3b() { }
void glNormal3bv() { }
void glNormal3d() { }
void glNormal3dv() { }
void glNormal3f() { }
void glNormal3fv() { }
void glNormal3i() { }
void glNormal3iv() { }
void glNormal3s() { }
void glNormal3sv() { }
void glNormalPointer() { }
void glNormalPointerEXT() { }
void glNormalStream3bATI() { }
void glNormalStream3bvATI() { }
void glNormalStream3dATI() { }
void glNormalStream3dvATI() { }
void glNormalStream3fATI() { }
void glNormalStream3fvATI() { }
void glNormalStream3iATI() { }
void glNormalStream3ivATI() { }
void glNormalStream3sATI() { }
void glNormalStream3svATI() { }
void glOrtho() { }
void glPNTrianglesfATI() { }
void glPNTrianglesiATI() { }
void glPassTexCoordATI() { }
void glPassThrough() { }
void glPixelMapfv() { }
void glPixelMapuiv() { }
void glPixelMapusv() { }
void glPixelStoref() { }
void glPixelStorei() { }
void glPixelTexGenParameterfSGIS() { }
void glPixelTexGenParameterfvSGIS() { }
void glPixelTexGenParameteriSGIS() { }
void glPixelTexGenParameterivSGIS() { }
void glPixelTexGenSGIX() { }
void glPixelTransferf() { }
void glPixelTransferi() { }
void glPixelZoom() { }
void glPointParameterf() { }
void glPointParameterfARB() { }
void glPointParameterfEXT() { }
void glPointParameterfSGIS() { }
void glPointParameterfv() { }
void glPointParameterfvARB() { }
void glPointParameterfvEXT() { }
void glPointParameterfvSGIS() { }
void glPointParameteri() { }
void glPointParameteriv() { }
void glPointSize() { }
unsigned int glPollAsyncSGIX() { return 0; }
unsigned int glPollInstrumentsSGIX() { return 0; }
void glPolygonMode() { }
void glPolygonOffset() { }
void glPolygonOffsetEXT() { }
void glPolygonStipple() { }
void glPopAttrib() { }
void glPopClientAttrib() { }
void glPopMatrix() { }
void glPopName() { }
void glPrioritizeTextures() { }
void glPrioritizeTexturesEXT() { }
void glProgramEnvParameter4dARB() { }
void glProgramEnvParameter4dvARB() { }
void glProgramEnvParameter4fARB() { }
void glProgramEnvParameter4fvARB() { }
void glProgramLocalParameter4dARB() { }
void glProgramLocalParameter4dvARB() { }
void glProgramLocalParameter4fARB() { }
void glProgramLocalParameter4fvARB() { }
void glProgramStringARB() { }
void glPushAttrib() { }
void glPushClientAttrib() { }
void glPushMatrix() { }
void glPushName() { }
void glRasterPos2d() { }
void glRasterPos2dv() { }
void glRasterPos2f() { }
void glRasterPos2fv() { }
void glRasterPos2i() { }
void glRasterPos2iv() { }
void glRasterPos2s() { }
void glRasterPos2sv() { }
void glRasterPos3d() { }
void glRasterPos3dv() { }
void glRasterPos3f() { }
void glRasterPos3fv() { }
void glRasterPos3i() { }
void glRasterPos3iv() { }
void glRasterPos3s() { }
void glRasterPos3sv() { }
void glRasterPos4d() { }
void glRasterPos4dv() { }
void glRasterPos4f() { }
void glRasterPos4fv() { }
void glRasterPos4i() { }
void glRasterPos4iv() { }
void glRasterPos4s() { }
void glRasterPos4sv() { }
void glReadBuffer() { }
void glReadInstrumentsSGIX() { }
void glReadPixels() { }
void glRectd() { }
void glRectdv() { }
void glRectf() { }
void glRectfv() { }
void glRecti() { }
void glRectiv() { }
void glRects() { }
void glRectsv() { }
void glReferencePlaneSGIX() { }
unsigned int glRenderMode() { return 0; }
void glResetHistogram() { }
void glResetHistogramEXT() { }
void glResetMinmax() { }
void glResetMinmaxEXT() { }
void glRotated() { }
void glRotatef() { }
void glSampleCoverage() { }
void glSampleCoverageARB() { }
void glSampleMapATI() { }
void glSampleMaskSGIS() { }
void glSamplePatternSGIS() { }
void glScaled() { }
void glScalef() { }
void glScissor() { }
void glSecondaryColor3b() { }
void glSecondaryColor3bEXT() { }
void glSecondaryColor3bv() { }
void glSecondaryColor3bvEXT() { }
void glSecondaryColor3d() { }
void glSecondaryColor3dEXT() { }
void glSecondaryColor3dv() { }
void glSecondaryColor3dvEXT() { }
void glSecondaryColor3f() { }
void glSecondaryColor3fEXT() { }
void glSecondaryColor3fv() { }
void glSecondaryColor3fvEXT() { }
void glSecondaryColor3i() { }
void glSecondaryColor3iEXT() { }
void glSecondaryColor3iv() { }
void glSecondaryColor3ivEXT() { }
void glSecondaryColor3s() { }
void glSecondaryColor3sEXT() { }
void glSecondaryColor3sv() { }
void glSecondaryColor3svEXT() { }
void glSecondaryColor3ub() { }
void glSecondaryColor3ubEXT() { }
void glSecondaryColor3ubv() { }
void glSecondaryColor3ubvEXT() { }
void glSecondaryColor3ui() { }
void glSecondaryColor3uiEXT() { }
void glSecondaryColor3uiv() { }
void glSecondaryColor3uivEXT() { }
void glSecondaryColor3us() { }
void glSecondaryColor3usEXT() { }
void glSecondaryColor3usv() { }
void glSecondaryColor3usvEXT() { }
void glSecondaryColorPointer() { }
void glSecondaryColorPointerEXT() { }
void glSelectBuffer() { }
void glSeparableFilter2D() { }
void glSeparableFilter2DEXT() { }
void glSetFragmentShaderConstantATI() { }
void glSetInvariantEXT() { }
void glSetLocalConstantEXT() { }
void glShadeModel() { }
void glShaderOp1EXT() { }
void glShaderOp2EXT() { }
void glShaderOp3EXT() { }
void glSharpenTexFuncSGIS() { }
void glSpriteParameterfSGIX() { }
void glSpriteParameterfvSGIX() { }
void glSpriteParameteriSGIX() { }
void glSpriteParameterivSGIX() { }
void glStartInstrumentsSGIX() { }
void glStencilFunc() { }
void glStencilFuncSeparateATI() { }
void glStencilMask() { }
void glStencilOp() { }
void glStencilOpSeparateATI() { }
void glStopInstrumentsSGIX() { }
void glSwizzleEXT() { }
void glTagSampleBufferSGIX() { }
void glTexBumpParameterfvATI() { }
void glTexBumpParameterivATI() { }
void glTexCoord1d() { }
void glTexCoord1dv() { }
void glTexCoord1f() { }
void glTexCoord1fv() { }
void glTexCoord1i() { }
void glTexCoord1iv() { }
void glTexCoord1s() { }
void glTexCoord1sv() { }
void glTexCoord2d() { }
void glTexCoord2dv() { }
void glTexCoord2f() { }
void glTexCoord2fv() { }
void glTexCoord2i() { }
void glTexCoord2iv() { }
void glTexCoord2s() { }
void glTexCoord2sv() { }
void glTexCoord3d() { }
void glTexCoord3dv() { }
void glTexCoord3f() { }
void glTexCoord3fv() { }
void glTexCoord3i() { }
void glTexCoord3iv() { }
void glTexCoord3s() { }
void glTexCoord3sv() { }
void glTexCoord4d() { }
void glTexCoord4dv() { }
void glTexCoord4f() { }
void glTexCoord4fv() { }
void glTexCoord4i() { }
void glTexCoord4iv() { }
void glTexCoord4s() { }
void glTexCoord4sv() { }
void glTexCoordPointer() { }
void glTexCoordPointerEXT() { }
void glTexEnvf() { }
void glTexEnvfv() { }
void glTexEnvi() { }
void glTexEnviv() { }
void glTexFilterFuncSGIS() { }
void glTexGend() { }
void glTexGendv() { }
void glTexGenf() { }
void glTexGenfv() { }
void glTexGeni() { }
void glTexGeniv() { }
void glTexImage1D() { }
void glTexImage2D() { }
void glTexImage3D() { }
void glTexImage3DEXT() { }
void glTexImage4DSGIS() { }
void glTexParameterf() { }
void glTexParameterfv() { }
void glTexParameteri() { }
void glTexParameteriv() { }
void glTexSubImage1D() { }
void glTexSubImage1DEXT() { }
void glTexSubImage2D() { }
void glTexSubImage2DEXT() { }
void glTexSubImage3D() { }
void glTexSubImage3DEXT() { }
void glTexSubImage4DSGIS() { }
void glTextureColorMaskSGIS() { }
void glTranslated() { }
void glTranslatef() { }
void glUnlockArraysEXT() { }
void glUnmapObjectBufferATI() { }
void glUpdateObjectBufferATI() { }
void glVariantArrayObjectATI() { }
void glVariantPointerEXT() { }
void glVariantbvEXT() { }
void glVariantdvEXT() { }
void glVariantfvEXT() { }
void glVariantivEXT() { }
void glVariantsvEXT() { }
void glVariantubvEXT() { }
void glVariantuivEXT() { }
void glVariantusvEXT() { }
void glVertex2d() { }
void glVertex2dv() { }
void glVertex2f() { }
void glVertex2fv() { }
void glVertex2i() { }
void glVertex2iv() { }
void glVertex2s() { }
void glVertex2sv() { }
void glVertex3d() { }
void glVertex3dv() { }
void glVertex3f() { }
void glVertex3fv() { }
void glVertex3i() { }
void glVertex3iv() { }
void glVertex3s() { }
void glVertex3sv() { }
void glVertex4d() { }
void glVertex4dv() { }
void glVertex4f() { }
void glVertex4fv() { }
void glVertex4i() { }
void glVertex4iv() { }
void glVertex4s() { }
void glVertex4sv() { }
void glVertexAttrib1dARB() { }
void glVertexAttrib1dvARB() { }
void glVertexAttrib1fARB() { }
void glVertexAttrib1fvARB() { }
void glVertexAttrib1sARB() { }
void glVertexAttrib1svARB() { }
void glVertexAttrib2dARB() { }
void glVertexAttrib2dvARB() { }
void glVertexAttrib2fARB() { }
void glVertexAttrib2fvARB() { }
void glVertexAttrib2sARB() { }
void glVertexAttrib2svARB() { }
void glVertexAttrib3dARB() { }
void glVertexAttrib3dvARB() { }
void glVertexAttrib3fARB() { }
void glVertexAttrib3fvARB() { }
void glVertexAttrib3sARB() { }
void glVertexAttrib3svARB() { }
void glVertexAttrib4NbvARB() { }
void glVertexAttrib4NivARB() { }
void glVertexAttrib4NsvARB() { }
void glVertexAttrib4NubARB() { }
void glVertexAttrib4NubvARB() { }
void glVertexAttrib4NuivARB() { }
void glVertexAttrib4NusvARB() { }
void glVertexAttrib4bvARB() { }
void glVertexAttrib4dARB() { }
void glVertexAttrib4dvARB() { }
void glVertexAttrib4fARB() { }
void glVertexAttrib4fvARB() { }
void glVertexAttrib4ivARB() { }
void glVertexAttrib4sARB() { }
void glVertexAttrib4svARB() { }
void glVertexAttrib4ubvARB() { }
void glVertexAttrib4uivARB() { }
void glVertexAttrib4usvARB() { }
void glVertexAttribArrayObjectATI() { }
void glVertexAttribPointerARB() { }
void glVertexBlendARB() { }
void glVertexBlendEnvfATI() { }
void glVertexBlendEnviATI() { }
void glVertexPointer() { }
void glVertexPointerEXT() { }
void glVertexStream2dATI() { }
void glVertexStream2dvATI() { }
void glVertexStream2fATI() { }
void glVertexStream2fvATI() { }
void glVertexStream2iATI() { }
void glVertexStream2ivATI() { }
void glVertexStream2sATI() { }
void glVertexStream2svATI() { }
void glVertexStream3dATI() { }
void glVertexStream3dvATI() { }
void glVertexStream3fATI() { }
void glVertexStream3fvATI() { }
void glVertexStream3iATI() { }
void glVertexStream3ivATI() { }
void glVertexStream3sATI() { }
void glVertexStream3svATI() { }
void glVertexStream4dATI() { }
void glVertexStream4dvATI() { }
void glVertexStream4fATI() { }
void glVertexStream4fvATI() { }
void glVertexStream4iATI() { }
void glVertexStream4ivATI() { }
void glVertexStream4sATI() { }
void glVertexStream4svATI() { }
void glViewport() { }
void glWeightPointerARB() { }
void glWeightbvARB() { }
void glWeightdvARB() { }
void glWeightfvARB() { }
void glWeightivARB() { }
void glWeightsvARB() { }
void glWeightubvARB() { }
void glWeightuivARB() { }
void glWeightusvARB() { }
void glWindowPos2d() { }
void glWindowPos2dARB() { }
void glWindowPos2dv() { }
void glWindowPos2dvARB() { }
void glWindowPos2f() { }
void glWindowPos2fARB() { }
void glWindowPos2fv() { }
void glWindowPos2fvARB() { }
void glWindowPos2i() { }
void glWindowPos2iARB() { }
void glWindowPos2iv() { }
void glWindowPos2ivARB() { }
void glWindowPos2s() { }
void glWindowPos2sARB() { }
void glWindowPos2sv() { }
void glWindowPos2svARB() { }
void glWindowPos3d() { }
void glWindowPos3dARB() { }
void glWindowPos3dv() { }
void glWindowPos3dvARB() { }
void glWindowPos3f() { }
void glWindowPos3fARB() { }
void glWindowPos3fv() { }
void glWindowPos3fvARB() { }
void glWindowPos3i() { }
void glWindowPos3iARB() { }
void glWindowPos3iv() { }
void glWindowPos3ivARB() { }
void glWindowPos3s() { }
void glWindowPos3sARB() { }
void glWindowPos3sv() { }
void glWindowPos3svARB() { }
void glWriteMaskEXT() { }
void* glXChooseVisual() { return 0; }
void glXCopyContext() { }
void glXCreateContext() { }
void glXCreateGLXPixmap() { }
void glXDestroyContext() { }
void glXDestroyGLXPixmap() { }
unsigned int glXGetConfig() { return 0; }
void glXGetCurrentContext() { }
void glXGetCurrentDrawable() { }
void glXIsDirect() { }
void glXMakeCurrent() { }
void glXQueryExtension() { }
void glXQueryVersion() { }
void glXSwapBuffers() { }
void glXUseXFont() { }
void glXWaitGL() { }
void glXWaitX() { }
void* glXGetClientString() { return 0; }
void* glXQueryServerString() { return 0; }
void* glXQueryExtensionsString() { return 0; }
void glXGetCurrentReadDrawable() { }
void* glXGetFBConfigs() { return 0; }
void* glXChooseFBConfig() { return 0; }
unsigned int glXGetFBConfigAttrib() { return 0; }
void* glXGetVisualFromFBConfig() { return 0; }
void glXCreatePixmap() { }
void glXDestroyPixmap() { }
void glXCreateNewContext() { }
unsigned int glXQueryContext() { return 0; }
void glXMakeContextCurrent() { }
void glXCreatePbuffer() { }
void glXDestroyPbuffer() { }
void glXQueryDrawable() { }
void glXSelectEvent() { }
void glXGetSelectedEvent() { }
void glXCreateWindow() { }
void glXDestroyWindow() { }
unsigned int glXGetVideoSyncSGI() { return 0; }
unsigned int glXWaitVideoSyncSGI() { return 0; }
unsigned int glXSwapIntervalSGI() { return 0; }
void glXMakeCurrentReadSGI() { }
void glXGetCurrentReadDrawableSGI() { }
unsigned int glXBindChannelToWindowSGIX() { return 0; }
unsigned int glXQueryChannelDeltasSGIX() { return 0; }
unsigned int glXChannelRectSGIX() { return 0; }
unsigned int glXQueryChannelRectSGIX() { return 0; }
unsigned int glXChannelRectSyncSGIX() { return 0; }
void* glXQueryHyperpipeNetworkSGIX() { return 0; }
unsigned int glXHyperpipeConfigSGIX() { return 0; }
unsigned int glXDestroyHyperpipeConfigSGIX() { return 0; }
void* glXQueryHyperpipeConfigSGIX() { return 0; }
unsigned int glXBindHyperpipeSGIX() { return 0; }
unsigned int glXQueryHyperpipeBestAttribSGIX() { return 0; }
unsigned int glXQueryHyperpipeAttribSGIX() { return 0; }
unsigned int glXHyperpipeAttribSGIX() { return 0; }
void glXCreateGLXVideoSourceSGIX() { }
void glXDestroyGLXVideoSourceSGIX() { }
unsigned int glXQueryContextInfoEXT() { return 0; }
void* glXGetCurrentDisplayEXT() { return 0; }
void* glXGetCurrentDisplay() { return 0; }
void glXGetContextIDEXT() { }
void glXImportContextEXT() { }
void glXFreeContextEXT() { }
void glXGetCurrentDrawableEXT() { }
unsigned int glXGetFBConfigAttribSGIX() { return 0; }
void* glXChooseFBConfigSGIX() { return 0; }
void glXCreateGLXPixmapWithConfigSGIX() { }
void glXCreateContextWithConfigSGIX() { }
void* glXGetVisualFromFBConfigSGIX() { return 0; }
void glXGetFBConfigFromVisualSGIX() { }
void* glXGetProcAddress() { return 0; }
void* glXGetProcAddressARB() { return 0; }
void glXCreateGLXPbufferSGIX() { }
void glXDestroyGLXPbufferSGIX() { }
unsigned int glXQueryGLXPbufferSGIX() { return 0; }
void glXSelectEventSGIX() { }
void glXGetSelectedEventSGIX() { }
void glXAssociateDMPbufferSGIX() { }
void glXJoinSwapGroupSGIX() { }
void glXBindSwapBarrierSGIX() { }
void glXQueryMaxSwapBarriersSGIX() { }
