#!/bin/sh
# sgugshell: Interactive SGUG environment shell
# Usage: sgugshell
#    or: chroot /opt/chroot /usr/sgug/bin/sgugshell
#
# Sets up PATH, LD_LIBRARYN32_PATH, and other environment variables,
# then drops into bash (or /bin/sh if bash isn't installed).
#
# Uses /bin/sh shebang so it can bootstrap itself on IRIX without
# requiring /usr/sgug/bin to be in PATH first.

# Clear conflicting build environment
unset PKG_CONFIG_PATH LDFLAGS CFLAGS CPPFLAGS CXXFLAGS
unset PERL M4 SED GREP BISON YACC
unset SHELL SHELL_PATH CONFIG_SHELL
unset CC CXX LD AR RANLIB
unset LD_LIBRARY_PATH LD_LIBRARYN32_PATH LD_LIBRARYN64_PATH
unset PYTHONPATH PYTHONHOME GCC_ROOT HOST

SGUG_ROOT=/usr/sgug
export PATH=$SGUG_ROOT/bin:$SGUG_ROOT/sbin:/usr/bin/X11:/usr/bin:/bin:/usr/sbin:/usr/bsd
export LD_LIBRARYN32_PATH=$SGUG_ROOT/lib32:/usr/lib32:/lib32:/usr/lib:/lib
export MANPATH=$SGUG_ROOT/share/man:/usr/share/catman/a_man:/usr/share/catman/g_man:/usr/share/catman/p_man:/usr/share/catman/u_man
export LC_ALL=C
export HOME=${HOME:-/root}
export TERM=${TERM:-vt100}

if [ -x /usr/sgug/bin/bash ]; then
    export PS1='[sgug] \w \$ '
    exec /usr/sgug/bin/bash --norc --noprofile
else
    export PS1='[sgug] $ '
    exec /bin/sh
fi
